import { describe, expect, it } from 'vitest';
import * as core from '@tarstate/core';
import * as adapter from '@tarstate/core/adapter';
import * as constraints from '@tarstate/core/constraints';
import * as db from '@tarstate/core/db';
import * as delta from '@tarstate/core/delta';
import * as diff from '@tarstate/core/diff';
import * as diagnostics from '@tarstate/core/diagnostics';
import * as evaluate from '@tarstate/core/evaluate';
import * as identity from '@tarstate/core/identity';
import * as materialization from '@tarstate/core/materialization';
import * as query from '@tarstate/core/query';
import * as runtime from '@tarstate/core/runtime';
import * as schema from '@tarstate/core/schema';
import * as source from '@tarstate/core/source';
import * as watch from '@tarstate/core/watch';
import * as writeApply from '@tarstate/core/write-apply';
import * as write from '@tarstate/core/write';

describe('tarstate core public exports', () => {
  it('keeps the root convenience barrel and taxonomy subpath imports available', () => {
    expect(core).toHaveProperty('defineSchema');
    expect(adapter).toHaveProperty('isRelationAdapter');
    expect(adapter).toHaveProperty('isRelationRuntime');
    expect(adapter).toHaveProperty('tryCommitAdapter');
    expect(adapter).toHaveProperty('tryApplyRelationPatches');
    expect(adapter).toHaveProperty('relationApplyResultFromAdapterCommit');
    expect(adapter).toHaveProperty('composeRelationRuntimes');
    expect(core).toHaveProperty('isRelationAdapter');
    expect(core).toHaveProperty('isRelationRuntime');
    expect(core).toHaveProperty('tryCommitAdapter');
    expect(core).toHaveProperty('tryApplyRelationPatches');
    expect(core).toHaveProperty('relationApplyResultFromAdapterCommit');
    expect(core).toHaveProperty('composeRelationRuntimes');
    expect(constraints).toHaveProperty('constrain');
    expect(constraints).toHaveProperty('tryTransactConstrained');
    expect(db).toHaveProperty('qMany');
    expect(db).not.toHaveProperty('tryTransactConstrained');
    expect(delta).toHaveProperty('relationDeltas');
    expect(diff).toHaveProperty('diffRows');
    expect(diagnostics).toBeDefined();
    expect(evaluate).toHaveProperty('evaluate');
    expect(identity).toHaveProperty('stableKey');
    expect(materialization).toHaveProperty('explainMaterialization');
    expect(materialization).toHaveProperty('materializedRowsFor');
    expect(materialization).toHaveProperty('materializedRowsForQuery');
    expect(materialization).toHaveProperty('materializedSourceFor');
    expect(materialization).toHaveProperty('snapshotIndex');
    expect(materialization).toHaveProperty('snapshotHashIndex');
    expect(core).toHaveProperty('materializedRowsFor');
    expect(core).toHaveProperty('materializedSourceFor');
    expect(core).toHaveProperty('snapshotHashIndex');
    expect(materialization).not.toHaveProperty('index');
    expect(materialization).not.toHaveProperty('materializationIndex');
    expect(core).not.toHaveProperty('index');
    expect(core).not.toHaveProperty('materializationIndex');
    expect(query).toHaveProperty('from');
    expect(query).toHaveProperty('setConcat');
    expect(runtime).toHaveProperty('trackTransact');
    expect(schema).toHaveProperty('relation');
    expect(schema).toHaveProperty('jsonField');
    expect(source).toHaveProperty('fromObjectSource');
    expect(source).not.toHaveProperty('asRelationSource');
    expect(watch).toHaveProperty('watch');
    expect(watch).toHaveProperty('subscribeWatch');
    expect(core).toHaveProperty('subscribeWatch');
    expect(watch).not.toHaveProperty('trackWatchedChanges');
    expect(watch).not.toHaveProperty('transferWatchRegistrations');
    expect(writeApply).toHaveProperty('applyWrites');
    expect(writeApply).toHaveProperty('applyWritesAtomic');
    expect(write).toHaveProperty('write');
    expect(write).toHaveProperty('insertOrUpdate');
    expect(write).toHaveProperty('deleteExact');
    expect(write).toHaveProperty('replaceAll');
    expect(write).not.toHaveProperty('applyWrites');
    expect(core).toHaveProperty('insertOrUpdate');
    expect(core).toHaveProperty('deleteExact');
    expect(core).toHaveProperty('replaceAll');
    expect(core).not.toHaveProperty('applyWrites');
  });
});
