export { composeRelationRuntimes, isRelationRuntime, tryApplyRelationPatches } from './stub.js';
export type {
  AdapterSnapshot,
  AdapterSource,
  ComposedRelationRuntimeVersion,
  MaybePromise,
  RelationApply,
  RelationApplyAcceptedResult,
  RelationApplyDurability,
  RelationApplyOptions,
  RelationApplyPartialResult,
  RelationApplyRejectedResult,
  RelationApplyReport,
  RelationApplyResult,
  RelationApplyStatus,
  RelationDelta,
  RelationLookup,
  RelationPatchTarget,
  RelationRangeBound,
  RelationRangeLookup,
  RelationRuntime,
  RelationRuntimeVersion,
  RelationSource,
  TarstateDiagnostic,
  WritePatch
} from './stub.js';
