export { collectDiagnostics, diagnostic, normalizeDiagnostics } from './diagnostics.js';
export type {
  TarstateCoreDiagnosticCode,
  TarstateDiagnostic,
  TarstateDiagnosticCode,
  TarstateDiagnosticMode,
  TarstateDiagnosticOptions,
  TarstateDiagnosticSeverity
} from './diagnostics.js';

export {
  anchoredPathField,
  booleanField,
  defineSchema,
  idField,
  isJsonValue,
  jsonField,
  nullable,
  numberField,
  optional,
  refField,
  relation,
  stringField
} from './schema.js';
export type { FieldSpec, JsonPrimitive, JsonValue, RelationRef } from './schema.js';

export {
  aggregate,
  and,
  any,
  as,
  asc,
  avg,
  bottom,
  bottomBy,
  btree,
  call,
  clauses,
  constRows,
  correlate,
  count,
  countDistinct,
  desc,
  difference,
  env,
  eq,
  expand,
  extend,
  field,
  from,
  gt,
  gte,
  hash,
  hostFn,
  intersection,
  isMissing,
  isNull,
  join,
  keyBy,
  leftJoin,
  limit,
  lookup,
  lt,
  lte,
  max,
  maxBy,
  maybe,
  min,
  minBy,
  neq,
  not,
  notAny,
  notMissing,
  notNull,
  or,
  pipe,
  project,
  qualify,
  queryKey,
  QueryKeyError,
  queryRowKeyFields,
  relationDependencies,
  rename,
  sel,
  sel1,
  self,
  setConcat,
  sort,
  sortLimit,
  sum,
  top,
  topBy,
  tuple,
  union,
  uniqueIndex,
  value,
  where,
  without
} from './query.js';
export type {
  AggregateConfig,
  AggregateExprData,
  AggregateFunction,
  AliasedQuery,
  AliasedRelationRef,
  ComparisonOp,
  CorrelationClauseMap,
  EquiJoinClauseMap,
  ExpandOptions,
  ExprData,
  ExprInput,
  HostExpressionFunction,
  HostFunction,
  NullSortOrder,
  OptionalProjection,
  PredicateData,
  PrimitiveValue,
  ProjectionData,
  Query,
  QueryData,
  QueryKeyInput,
  RowExprData,
  SortData,
  SortDirection,
  SortInput
} from './query.js';

export {
  DbTransactionError,
  createDb,
  exists,
  getEnv,
  q,
  qMany,
  qManyResult,
  qResult,
  row,
  setEnvTx,
  stripMeta,
  transact,
  tryTransact,
  updateEnv,
  whatIf,
  withEnv
} from './db.js';
export type {
  Db,
  DbData,
  DbEnv,
  DbEnvUpdate,
  DbInputData,
  DbInputEnv,
  DbOptions,
  DbQueryIntoResult,
  DbQueryOptions,
  DbQuerySort,
  DbQuerySortKey,
  DbTransactionBuilder,
  DbTransactionContext,
  DbTransactionInput,
  DbTransactionInputs,
  DbTransactionItem,
  DbTransactionOptions,
  DbTransactionResult,
  MappedQueryBatchResult,
  MappedQueryBatchRows,
  QueryBatch,
  QueryBatchResult,
  QueryBatchRows,
  QueryBatchTarget,
  QueryBatchTargetRow,
  RelationKeyValue,
  RowLookupOptions,
  RowPredicateOptions,
  SetEnvTransaction
} from './db.js';

export {
  check,
  constrain,
  fk,
  req,
  unique,
  validateConstraints
} from './constraints.js';
export type {
  CheckConstraintData,
  ConstraintData,
  ConstraintOptions,
  ConstraintRelationField,
  ConstraintRelationFields,
  ConstraintRelationRow,
  ConstraintSet,
  ConstraintValidationInput,
  ConstraintValidationOptions,
  ConstraintValidationResult,
  ForeignKeyCascade,
  ForeignKeyConstraintData,
  QueryForeignKeyConstraintData,
  QueryRequiredConstraintData,
  QueryUniqueConstraintData,
  RequiredConstraintData,
  UniqueConstraintData
} from './constraints.js';

export { createStore } from './store.js';
export type {
  Store,
  StoreCommit,
  StoreCommitInput,
  StoreCommitOptions,
  StoreCommitResult,
  StoreCommitStatus,
  StoreMappedQueryBatchResult,
  StoreQueries,
  StoreQuery,
  StoreQueryBatchResult,
  StoreQueryOptions,
  StoreQueryResult,
  StoreSeedInput,
  StoreView,
  StoreViewSnapshot,
  StoreWhatIf
} from './store.js';

export {
  deleteByKey,
  deleteExact,
  deleteRows,
  insert,
  insertIgnore,
  insertOrMerge,
  insertOrReplace,
  insertOrUpdate,
  isWritePatch,
  replaceAll,
  seed,
  update,
  updateByKey,
  write,
  writeInputPatches
} from './write.js';
export type {
  DeleteByKeyPatch,
  DeleteExactPatch,
  DeletePatch,
  InsertIgnorePatch,
  InsertOrMergeOptions,
  InsertOrMergePatch,
  InsertOrReplacePatch,
  InsertOrUpdateOptions,
  InsertOrUpdatePatch,
  InsertPatch,
  RelationKeyInput,
  RelationMergeInput,
  RelationRow,
  RelationRowUpdate,
  RelationRowUpdateInput,
  RelationSchema,
  RelationWriter,
  ReplaceAllPatch,
  SchemaSeedInput,
  SchemaSeedPatch,
  SchemaSeedPatches,
  UpdateByKeyPatch,
  UpdatePatch,
  WriteInput,
  WritePatch
} from './write.js';
