export {
  demat,
  explainMaterialization,
  isMaterialized,
  maintainMaterializationSnapshots,
  maintainMaterializations,
  mat,
  materializationForQuery,
  materializationsFor,
  materializedRelationFor,
  materializedRelationForQuery,
  materializedRowsFor,
  materializedRowsForQuery,
  materializedSourceFor,
  readMaterializedQuery,
} from './impl.js';
export type {
  MaterializableDb,
  MaterializationEnvDelta,
  MaterializationExplanation,
  MaterializationIndexSpec,
  MaterializationInput,
  MaterializationMaintenanceChange,
  MaterializationMaintenanceDecision,
  MaterializationMaintenanceKind,
  MaterializationMaintenanceOptions,
  MaterializationMaintenanceResult,
  MaterializationMaintainResult,
  MaterializationMetadata,
  MaterializationMode,
  MaterializationOptions,
  MaterializationRange,
  MaterializationRangeBound,
  MaterializationRefreshResult,
  MaterializationTarget,
  MaterializedDb,
  MaterializedQueryResult,
  SnapshotMaterializationOptions,
  SnapshotMaterializationTarget,
} from './impl.js';
