import { canonicalizeJson, type JsonValue } from '@tarstate/core';
import type { PreparedArtifactBuildManifest } from './model.js';

export const renderArtifactBindings = (manifest: PreparedArtifactBuildManifest): string => {
  const lines = ['// Generated by @tarstate/schema-tools. Do not edit.'];
  if (manifest.relations.length > 0) {
    lines.push("import type { LiteralRelation, SchemaKey, SchemaRow } from '@tarstate/core/schema';");
  }
  lines.push('');
  for (const [name, artifact] of Object.entries(manifest.artifacts).sort(compareEntries)) {
    lines.push(
      'export const ' + name + 'ArtifactRef = '
      + JSON.stringify({ id: artifact.id, contentHash: artifact.contentHash })
      + ' as const;'
    );
  }
  const declarationNames = Object.keys(manifest.declarations).sort();
  if (declarationNames.length > 0) {
    lines.push('export const artifactDeclarationNames = ' + JSON.stringify(
      Object.fromEntries(declarationNames.map((name) => [name, name]))
    ) + ' as const;');
  }
  if (Object.keys(manifest.artifacts).length > 0 || declarationNames.length > 0) lines.push('');

  const emittedSchemas = new Set<string>();
  for (const binding of manifest.relations) {
    const schemaBodyName = binding.schemaName + 'SchemaBody';
    if (!emittedSchemas.has(binding.schemaName)) {
      emittedSchemas.add(binding.schemaName);
      lines.push('declare const ' + schemaBodyName + ': ' + renderTypeLiteral(binding.schemaBody) + ';', '');
    }
    const relation = binding.schema.relationsByName.get(binding.relationName);
    if (relation === undefined) throw new Error('Prepared relation disappeared during rendering');
    const relationName = binding.name + 'Relation';
    const typeName = binding.name[0]!.toUpperCase() + binding.name.slice(1);
    lines.push(
      'export const ' + relationName + ': LiteralRelation<typeof ' + schemaBodyName + ', ' + JSON.stringify(binding.relationName) + '> = {',
      '  schemaView: ' + binding.schemaName + 'ArtifactRef,',
      '  relationId: ' + JSON.stringify(relation.declaration.relationId) + ',',
      '  name: ' + JSON.stringify(binding.relationName) + ',',
      '  declaration: ' + canonicalizeJson(relation.declaration as unknown as JsonValue),
      '};',
      'export type ' + typeName + 'Row = SchemaRow<typeof ' + schemaBodyName + ', ' + JSON.stringify(binding.relationName) + '>;',
      'export type ' + typeName + 'Key = SchemaKey<typeof ' + schemaBodyName + ', ' + JSON.stringify(binding.relationName) + '>;',
      ''
    );
  }
  return lines.join('\n');
};

const renderTypeLiteral = (value: unknown): string => {
  if (value === null) return 'null';
  if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') {
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) return 'readonly [' + value.map(renderTypeLiteral).join(', ') + ']';
  if (!isRecord(value)) throw new TypeError('Schema body is not portable JSON');
  const members = Object.entries(value)
    .sort(compareEntries)
    .map(([key, member]) => 'readonly ' + JSON.stringify(key) + ': ' + renderTypeLiteral(member));
  return '{ ' + members.join('; ') + ' }';
};

const compareEntries = ([left]: readonly [string, unknown], [right]: readonly [string, unknown]): number =>
  left < right ? -1 : left > right ? 1 : 0;
const isRecord = (value: unknown): value is Readonly<Record<string, unknown>> =>
  value !== null && typeof value === 'object' && !Array.isArray(value);
