import { safeParseArtifactValue, type ArtifactParseBudget, type JsonValue, type ParseResult } from '@tarstate/core';
import {
  prepareSchema,
  type FieldDeclaration,
  type PreparedSchema,
  type ScalarDeclaration,
  type SchemaArtifact
} from '@tarstate/core/schema';
import { schemaToolsFailure } from './internal-issues.js';

export type { SchemaArtifact } from '@tarstate/core/schema';

export type PreparedSchemaTooling = {
  readonly artifact: SchemaArtifact;
  readonly schema: PreparedSchema;
};

export type GeneratedSchemaOutputs = {
  readonly typescript: string;
  readonly jsonSchema: JsonValue;
  readonly jsonSchemaText: string;
  readonly markdown: string;
};

/** Parses and resolves a schema artifact for deterministic tooling output. */
export const safePrepareSchemaArtifact = async (input: unknown, budget?: ArtifactParseBudget): Promise<ParseResult<PreparedSchemaTooling>> => {
  const parsed = await safeParseArtifactValue(input, budget);
  if (!parsed.success) return parsed;
  if (parsed.value.kind !== 'schema') return schemaToolsFailure('schema_tools.artifact_kind', { expected: 'schema', actual: parsed.value.kind });
  const prepared = prepareSchema(parsed.value.body);
  if (!prepared.success) return prepared;
  return { success: true, value: { artifact: parsed.value as SchemaArtifact, schema: prepared.value }, issues: [] };
};

/** Generates matching TypeScript, JSON Schema, and Markdown from one validated artifact. */
export const generateSchemaOutputs = async (input: unknown, budget?: ArtifactParseBudget): Promise<ParseResult<GeneratedSchemaOutputs>> => {
  const prepared = await safePrepareSchemaArtifact(input, budget);
  if (!prepared.success) return prepared;
  const jsonSchema = generateJsonSchema(prepared.value);
  return {
    success: true,
    value: {
      typescript: renderTypeScriptDeclarations(prepared.value),
      jsonSchema,
      jsonSchemaText: renderJson(jsonSchema),
      markdown: renderSchemaMarkdown(prepared.value)
    },
    issues: []
  };
};

export const renderTypeScriptDeclarations = ({ artifact, schema }: PreparedSchemaTooling): string => {
  const names = relationTypeNames(schema);
  const lines = [
    '// Generated by @tarstate/schema-tools. Do not edit.',
    '// Schema: ' + artifact.id,
    '// Content hash: ' + artifact.contentHash,
    '',
    'export type JsonValue = null | boolean | number | string | readonly JsonValue[] | { readonly [key: string]: JsonValue };',
    "export type TarstateTaggedValue = Readonly<{ kind: 'tarstate.value'; type: string; value: JsonValue }>;",
    '',
    'export const schemaRef = ' + JSON.stringify({ id: artifact.id, contentHash: artifact.contentHash }) + ' as const;',
    ''
  ];
  for (const relation of sortedRelations(schema)) {
    const typeName = names.get(relation.declaration.relationId) as string;
    lines.push('/** ' + safeComment(relation.declaration.description ?? relation.declaration.relationId) + ' */');
    lines.push('export interface ' + typeName + 'Row {');
    for (const [fieldName, field] of sortedEntries(relation.declaration.fields)) {
      const optional = field.optional === true ? '?' : '';
      const nullable = field.nullable === true ? ' | null' : '';
      lines.push('  readonly ' + propertyName(fieldName) + optional + ': ' + scalarTypeScript(field.type, names) + nullable + ';');
    }
    lines.push('}');
    const keyTypes = relation.declaration.key.map((fieldName) => scalarTypeScript(relation.declaration.fields[fieldName]!.type, names));
    lines.push('export type ' + typeName + 'Key = readonly [' + keyTypes.join(', ') + '];');
    lines.push('');
  }
  lines.push('export interface SchemaRelations {');
  for (const relation of sortedRelations(schema)) {
    const typeName = names.get(relation.declaration.relationId) as string;
    lines.push('  readonly ' + JSON.stringify(relation.name) + ': Readonly<{ relationId: ' + JSON.stringify(relation.declaration.relationId) + '; row: ' + typeName + 'Row; key: ' + typeName + 'Key }>;');
  }
  lines.push('}', '');
  return lines.join('\n');
};

export const generateJsonSchema = ({ artifact, schema }: PreparedSchemaTooling): JsonValue => {
  const names = relationTypeNames(schema);
  const definitions: Record<string, JsonValue> = {};
  const properties: Record<string, JsonValue> = {};
  for (const relation of sortedRelations(schema)) {
    const typeName = names.get(relation.declaration.relationId) as string;
    const fieldProperties: Record<string, JsonValue> = {};
    const required: string[] = [];
    for (const [fieldName, field] of sortedEntries(relation.declaration.fields)) {
      fieldProperties[fieldName] = fieldJsonSchema(field, names);
      if (field.optional !== true) required.push(fieldName);
    }
    definitions[typeName + 'Row'] = {
      type: 'object',
      additionalProperties: false,
      properties: fieldProperties,
      required,
      ...(relation.declaration.description === undefined ? {} : { description: relation.declaration.description })
    };
    definitions[typeName + 'Key'] = {
      type: 'array',
      prefixItems: relation.declaration.key.map((fieldName) => scalarJsonSchema(relation.declaration.fields[fieldName]!.type, names)),
      minItems: relation.declaration.key.length,
      maxItems: relation.declaration.key.length
    };
    properties[relation.name] = { type: 'array', items: { $ref: '#/$defs/' + typeName + 'Row' } };
  }
  return {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: artifact.id + '?contentHash=' + artifact.contentHash,
    title: artifact.body.description ?? artifact.id,
    type: 'object',
    additionalProperties: false,
    properties,
    required: sortedRelations(schema).map(({ name }) => name),
    $defs: definitions,
    'x-tarstate-schema-ref': { id: artifact.id, contentHash: artifact.contentHash }
  };
};

export const renderSchemaMarkdown = ({ artifact, schema }: PreparedSchemaTooling): string => {
  const lines = [
    '# ' + markdownText(artifact.body.description ?? artifact.id),
    '',
    '- Schema ID: ' + markdownCode(artifact.id),
    '- Content hash: ' + markdownCode(artifact.contentHash),
    ''
  ];
  for (const relation of sortedRelations(schema)) {
    lines.push('## ' + markdownText(relation.name), '');
    if (relation.declaration.description !== undefined) lines.push(markdownText(relation.declaration.description), '');
    lines.push('- Relation ID: ' + markdownCode(relation.declaration.relationId));
    lines.push('- Logical key: ' + relation.declaration.key.map(markdownCode).join(', '), '');
    lines.push('| Field | Type | Optional | Nullable | Description |', '| --- | --- | --- | --- | --- |');
    for (const [fieldName, field] of sortedEntries(relation.declaration.fields)) {
      lines.push('| ' + markdownCode(fieldName) + ' | ' + markdownCode(scalarLabel(field.type)) + ' | ' + yesNo(field.optional) + ' | ' + yesNo(field.nullable) + ' | ' + markdownText(field.description ?? '') + ' |');
    }
    lines.push('');
  }
  return lines.join('\n');
};

const fieldJsonSchema = (field: FieldDeclaration, names: ReadonlyMap<string, string>): JsonValue => {
  const scalar = scalarJsonSchema(field.type, names);
  const schema = field.nullable === true ? { anyOf: [scalar, { type: 'null' }] } : scalar;
  return field.description === undefined ? schema : { ...schema as Readonly<Record<string, JsonValue>>, description: field.description };
};

const scalarJsonSchema = (scalar: ScalarDeclaration, names: ReadonlyMap<string, string>): JsonValue => {
  if (scalar.kind === 'string') return scalar.values === undefined ? { type: 'string' } : { type: 'string', enum: [...scalar.values] };
  if (scalar.kind === 'boolean') return { type: 'boolean' };
  if (scalar.kind === 'number') return { type: 'number' };
  if (scalar.kind === 'integer') return { type: 'integer', minimum: Number.MIN_SAFE_INTEGER, maximum: Number.MAX_SAFE_INTEGER };
  if (scalar.kind === 'json') return {};
  if (scalar.kind === 'ref') return { $ref: '#/$defs/' + requiredRelationTypeName(names, scalar.target.relationId) + 'Key' };
  const type = scalar.kind === 'custom' ? undefined : scalar.kind;
  const taggedProperties: Record<string, JsonValue> = {
    kind: { const: 'tarstate.value' },
    type: type === undefined ? { type: 'string' } : { const: type },
    value: scalar.kind === 'custom' ? {} : { type: 'string' }
  };
  if (scalar.kind === 'decimal') taggedProperties.value = { type: 'string', pattern: '^(?!-0$)-?(?:0|[1-9][0-9]*)(?:\\.[0-9]*[1-9])?$' };
  if (scalar.kind === 'instant') {
    const fraction = scalar.precision === 'millisecond' ? '[0-9]{3}0{6}' : scalar.precision === 'microsecond' ? '[0-9]{6}0{3}' : '[0-9]{9}';
    taggedProperties.value = { type: 'string', pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.' + fraction + 'Z$' };
  }
  if (scalar.kind === 'bytes') taggedProperties.value = { type: 'string', pattern: '^[A-Za-z0-9_-]*$', 'x-tarstate-canonical-base64url': true };
  return { type: 'object', additionalProperties: false, required: ['kind', 'type', 'value'], properties: taggedProperties };
};

const scalarTypeScript = (scalar: ScalarDeclaration, names: ReadonlyMap<string, string>): string => {
  if (scalar.kind === 'string') return scalar.values === undefined ? 'string' : scalar.values.map((value) => JSON.stringify(value)).join(' | ');
  if (scalar.kind === 'boolean') return 'boolean';
  if (scalar.kind === 'number' || scalar.kind === 'integer') return 'number';
  if (scalar.kind === 'json') return 'JsonValue';
  if (scalar.kind === 'ref') return requiredRelationTypeName(names, scalar.target.relationId) + 'Key';
  if (scalar.kind === 'custom') return 'TarstateTaggedValue';
  return "Readonly<{ kind: 'tarstate.value'; type: " + JSON.stringify(scalar.kind) + '; value: string }>';
};

const scalarLabel = (scalar: ScalarDeclaration): string => {
  if (scalar.kind === 'string' && scalar.values !== undefined) return 'string(' + scalar.values.join(' | ') + ')';
  if (scalar.kind === 'instant') return 'instant/' + scalar.precision;
  if (scalar.kind === 'ref') return 'ref(' + scalar.target.relationId + ')';
  if (scalar.kind === 'custom') return 'custom(' + scalar.codec.id + '@' + scalar.codec.version + ')';
  return scalar.kind;
};

const requiredRelationTypeName = (names: ReadonlyMap<string, string>, relationId: string): string => {
  const name = names.get(relationId);
  if (name === undefined) throw new Error('Prepared schema contains an unresolved relation reference: ' + relationId);
  return name;
};

const renderJson = (value: JsonValue): string => JSON.stringify(value, undefined, 2) + '\n';

const relationTypeNames = (schema: PreparedSchema): ReadonlyMap<string, string> => {
  const output = new Map<string, string>();
  const used = new Set<string>();
  for (const relation of sortedRelations(schema)) {
    const base = pascalIdentifier(relation.name) || 'Relation';
    let candidate = base;
    let suffix = 2;
    while (used.has(candidate)) candidate = base + suffix++;
    used.add(candidate);
    output.set(relation.declaration.relationId, candidate);
  }
  return output;
};

const sortedRelations = (schema: PreparedSchema) => [...schema.relationsByName.values()].sort((left, right) => compare(left.name, right.name));
const sortedEntries = <Value>(record: Readonly<Record<string, Value>>): readonly (readonly [string, Value])[] => Object.entries(record).sort(([left], [right]) => compare(left, right));
const compare = (left: string, right: string): number => left < right ? -1 : left > right ? 1 : 0;
const pascalIdentifier = (value: string): string => value.split(/[^A-Za-z0-9]+/u).filter(Boolean).map((part) => part[0]!.toUpperCase() + part.slice(1)).join('').replace(/^[0-9]/u, '_$&');
const propertyName = (value: string): string => /^[$A-Z_a-z][$\w]*$/u.test(value) ? value : JSON.stringify(value);
const safeComment = (value: string): string => value.replaceAll('*/', '* /').replaceAll(/\s+/gu, ' ').trim();
const markdownCode = (value: string): string => {
  const longestFence = Math.max(0, ...[...value.matchAll(/`+/gu)].map(([ticks]) => ticks.length));
  const fence = '`'.repeat(longestFence + 1);
  const padding = /^[ `]|[ `]$/u.test(value) ? ' ' : '';
  return fence + padding + value.replaceAll('|', '\\|') + padding + fence;
};
const markdownText = (value: string): string => value.replaceAll(/\r?\n/gu, ' ').replaceAll('\\', '\\\\').replaceAll(/([#&*<>_`|]|\[|\])/gu, '\\$1');
const yesNo = (value: boolean | undefined): string => value === true ? 'yes' : 'no';
