import { canonicalSchemaManifest, type FieldManifestV1, type SchemaManifestV1 } from '@tarstate/core/schema';
import { keyFields, sortedEntries, stringLiteral, tsPropertyName, uniqueTypeName } from './names.js';

export type TypeScriptRowsOptions = {
  readonly header?: string;
};

export function emitTypeScriptRows(input: SchemaManifestV1, options: TypeScriptRowsOptions = {}): string {
  return emitTypeScriptRowsForCanonicalManifest(canonicalSchemaManifest(input), options);
}

export function emitTypeScriptRowsForCanonicalManifest(
  manifest: SchemaManifestV1,
  options: TypeScriptRowsOptions = {}
): string {
  const usedNames = new Set<string>(['JsonPrimitive', 'JsonValue', 'NonNullJsonValue', 'SchemaRows', 'SchemaKeys']);
  const relationNames = new Map<string, string>();
  const relationKeyNames = new Map<string, string>();
  const codecNames = new Map<string, string>();

  for (const relationName of Object.keys(manifest.relations).sort()) {
    relationNames.set(relationName, uniqueTypeName(relationName, 'Row', usedNames));
  }
  for (const relationName of Object.keys(manifest.relations).sort()) {
    relationKeyNames.set(relationName, uniqueTypeName(relationName, 'Key', usedNames));
  }
  for (const codecName of Object.keys(manifest.codecs ?? {}).sort()) {
    codecNames.set(codecName, uniqueTypeName(codecName, 'Value', usedNames));
  }

  const lines: string[] = [
    options.header ?? '// Generated by @tarstate/schema-tools. Do not edit by hand.',
    '',
    'export type JsonPrimitive = string | number | boolean | null;',
    'export type JsonValue = JsonPrimitive | readonly JsonValue[] | { readonly [key: string]: JsonValue };',
    'export type NonNullJsonValue = Exclude<JsonPrimitive, null> | readonly JsonValue[] | { readonly [key: string]: JsonValue };'
  ];

  if ((manifest.codecs !== undefined && Object.keys(manifest.codecs).length > 0) || hasCustomField(manifest)) {
    lines.push('');
    for (const codecName of sortedEntries(manifest.codecs ?? {})) {
      const typeName = codecNames.get(codecName[0]) ?? uniqueTypeName(codecName[0], 'Value', usedNames);
      codecNames.set(codecName[0], typeName);
      lines.push(`export type ${typeName} = unknown;`);
    }
  }

  for (const [relationName, relation] of sortedEntries(manifest.relations)) {
    const rowTypeName = relationNames.get(relationName);
    if (rowTypeName === undefined) continue;
    lines.push('', `export type ${rowTypeName} = {`);
    for (const [fieldName, field] of sortedEntries(relation.fields)) {
      const optional = field.optional === true ? '?' : '';
      lines.push(`  readonly ${tsPropertyName(fieldName)}${optional}: ${typeScriptFieldType(field, codecNames)};`);
    }
    lines.push('};');
    const keyTypeName = relationKeyNames.get(relationName);
    if (keyTypeName !== undefined) lines.push(`export type ${keyTypeName} = ${typeScriptKeyType(rowTypeName, keyFields(relation.key))};`);
  }

  lines.push('', 'export type SchemaRows = {');
  for (const [relationName] of sortedEntries(manifest.relations)) {
    const rowTypeName = relationNames.get(relationName);
    if (rowTypeName !== undefined) lines.push(`  readonly ${tsPropertyName(relationName)}: ${rowTypeName};`);
  }
  lines.push('};');
  lines.push('', 'export type SchemaKeys = {');
  for (const [relationName] of sortedEntries(manifest.relations)) {
    const keyTypeName = relationKeyNames.get(relationName);
    if (keyTypeName !== undefined) lines.push(`  readonly ${tsPropertyName(relationName)}: ${keyTypeName};`);
  }
  lines.push('};');
  lines.push('', `export type SchemaId = ${stringLiteral(manifest.schemaId)};`, '');
  return lines.join('\n');
}

function typeScriptFieldType(field: FieldManifestV1, codecNames: ReadonlyMap<string, string>): string {
  const base = typeScriptFieldBaseType(field, codecNames);
  return field.nullable === true ? `${base} | null` : base;
}

function typeScriptFieldBaseType(field: FieldManifestV1, codecNames: ReadonlyMap<string, string>): string {
  switch (field.type) {
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'json':
      return 'NonNullJsonValue';
    case 'custom':
      return codecNames.get(field.codec) ?? 'unknown';
    case 'string':
    case 'id':
    case 'ref':
    case 'anchoredPath':
      return 'string';
  }
}

function typeScriptKeyType(rowTypeName: string, fields: readonly string[]): string {
  if (fields.length === 1) return `${rowTypeName}[${stringLiteral(fields[0] ?? '')}]`;
  return `readonly [${fields.map((fieldName) => `${rowTypeName}[${stringLiteral(fieldName)}]`).join(', ')}]`;
}

function hasCustomField(manifest: SchemaManifestV1): boolean {
  return Object.values(manifest.relations).some((relation) => Object.values(relation.fields).some((field) => field.type === 'custom'));
}
