import {
  canonicalSchemaManifest,
  type FieldManifestV1,
  type RelationManifestV1,
  type SchemaManifestV1
} from '@tarstate/core/schema';
import { keyFields, sortedEntries, stringLiteral, tsPropertyName, uniqueTypeName } from './names.js';

export type TypeScriptRowsOptions = {
  readonly header?: string;
};

export function emitTypeScriptRows(input: SchemaManifestV1, options: TypeScriptRowsOptions = {}): string {
  return emitTypeScriptRowsForCanonicalManifest(canonicalSchemaManifest(input), options);
}

export function emitTypeScriptRowsForCanonicalManifest(
  manifest: SchemaManifestV1,
  options: TypeScriptRowsOptions = {}
): string {
  const names = generatedTypeNames(manifest);
  return [
    options.header ?? '// Generated by @tarstate/schema-tools. Do not edit by hand.',
    '',
    'export type JsonPrimitive = string | number | boolean | null;',
    'export type JsonValue = JsonPrimitive | readonly JsonValue[] | { readonly [key: string]: JsonValue };',
    'export type NonNullJsonValue = Exclude<JsonPrimitive, null> | readonly JsonValue[] | { readonly [key: string]: JsonValue };',
    ...codecTypeLines(manifest, names.codecNames),
    ...sortedEntries(manifest.relations).flatMap(([relationName, relation]) =>
      relationTypeLines(relationName, relation, names)
    ),
    ...schemaIndexLines(manifest, names),
    ''
  ].join('\n');
}

type GeneratedTypeNames = {
  readonly relationNames: ReadonlyMap<string, string>;
  readonly relationKeyNames: ReadonlyMap<string, string>;
  readonly codecNames: ReadonlyMap<string, string>;
};

function generatedTypeNames(manifest: SchemaManifestV1): GeneratedTypeNames {
  const usedNames = new Set<string>(['JsonPrimitive', 'JsonValue', 'NonNullJsonValue', 'SchemaRows', 'SchemaKeys']);
  const relationNames = generatedTypeNameMap(Object.keys(manifest.relations).sort(), 'Row', usedNames);
  const relationKeyNames = generatedTypeNameMap(Object.keys(manifest.relations).sort(), 'Key', usedNames);
  const codecNames = generatedTypeNameMap(Object.keys(manifest.codecs ?? {}).sort(), 'Value', usedNames);

  return { relationNames, relationKeyNames, codecNames };
}

function generatedTypeNameMap<const Suffix extends string>(
  names: readonly string[],
  suffix: Suffix,
  usedNames: Set<string>
): ReadonlyMap<string, string> {
  return new Map(names.map((name) => [name, uniqueTypeName(name, suffix, usedNames)] as const));
}

function codecTypeLines(manifest: SchemaManifestV1, codecNames: ReadonlyMap<string, string>): readonly string[] {
  if ((manifest.codecs === undefined || Object.keys(manifest.codecs).length === 0) && !hasCustomField(manifest)) {
    return [];
  }
  return [
    '',
    ...sortedEntries(manifest.codecs ?? {}).map(([codecName]) =>
      `export type ${requiredTypeName(codecNames, codecName)} = unknown;`
    )
  ];
}

function relationTypeLines(
  relationName: string,
  relation: RelationManifestV1,
  names: GeneratedTypeNames
): readonly string[] {
  const rowTypeName = requiredTypeName(names.relationNames, relationName);
  const keyTypeName = requiredTypeName(names.relationKeyNames, relationName);
  return [
    '',
    `export type ${rowTypeName} = {`,
    ...sortedEntries(relation.fields).map(([fieldName, field]) => {
      const optional = field.optional === true ? '?' : '';
      return `  readonly ${tsPropertyName(fieldName)}${optional}: ${typeScriptFieldType(field, names.codecNames)};`;
    }),
    '};',
    `export type ${keyTypeName} = ${typeScriptKeyType(rowTypeName, keyFields(relation.key))};`
  ];
}

function schemaIndexLines(manifest: SchemaManifestV1, names: GeneratedTypeNames): readonly string[] {
  return [
    '',
    'export type SchemaRows = {',
    ...sortedEntries(manifest.relations).map(([relationName]) =>
      `  readonly ${tsPropertyName(relationName)}: ${requiredTypeName(names.relationNames, relationName)};`
    ),
    '};',
    '',
    'export type SchemaKeys = {',
    ...sortedEntries(manifest.relations).map(([relationName]) =>
      `  readonly ${tsPropertyName(relationName)}: ${requiredTypeName(names.relationKeyNames, relationName)};`
    ),
    '};',
    '',
    `export type SchemaId = ${stringLiteral(manifest.schemaId)};`
  ];
}

function requiredTypeName(names: ReadonlyMap<string, string>, sourceName: string): string {
  const typeName = names.get(sourceName);
  if (typeName === undefined) throw new Error(`Generated TypeScript name missing for ${sourceName}`);
  return typeName;
}

function typeScriptFieldType(field: FieldManifestV1, codecNames: ReadonlyMap<string, string>): string {
  const base = typeScriptFieldBaseType(field, codecNames);
  return field.nullable === true ? `${base} | null` : base;
}

function typeScriptFieldBaseType(field: FieldManifestV1, codecNames: ReadonlyMap<string, string>): string {
  switch (field.type) {
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'json':
      return 'NonNullJsonValue';
    case 'custom':
      return codecNames.get(field.codec) ?? 'unknown';
    case 'string':
    case 'id':
    case 'ref':
    case 'anchoredPath':
      return 'string';
  }
}

function typeScriptKeyType(rowTypeName: string, fields: readonly string[]): string {
  if (fields.length === 1) return `${rowTypeName}[${stringLiteral(fields[0] ?? '')}]`;
  return `readonly [${fields.map((fieldName) => `${rowTypeName}[${stringLiteral(fieldName)}]`).join(', ')}]`;
}

function hasCustomField(manifest: SchemaManifestV1): boolean {
  return Object.values(manifest.relations).some((relation) =>
    Object.values(relation.fields).some((field) => field.type === 'custom')
  );
}
